# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
        - 5432:5432

  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://example:example@db:5432/postgres
    ports:
      - 8000:8000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
